name: Auto Pull on Test Update

on:
  push:
    branches:
      - Test

jobs:
  pull:
    runs-on: windows-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"  

    - name: Pull latest changes
      run: |
        git checkout Test 
        git pull origin Test 
